### PR TITLE
Change error handling from harbinger to errbit

### LINKED ISSUE #204: Change error handling from harbinger to errbit
We are using [harbinger](https://github.com/ndlib/harbinger) to capture exceptions in CurateND. The rest of our applications have standardized around [errbit](https://github.com/errbit/errbit). Deprecate the old system in implement the new one.

### PR DESCRIPTION
**Pull request by jeremyf**
## Claiming issue 204

@f5cf42762c68af2458e7118d32501dbb17cd6b97

relates to #204

$ ./script/start-issue 204

[skip ci]

## Adding Airbrake prior version

@78ff3b467962bfa6a38845c4111e98a52ecb678a

```console
$ bundle
```

## Creating airbrake configuration/initialization

@fc223c034aef52fb6efb7c4c20acd9416e8ac135

## Replacing Harbinger usage with Airbrake

@f9a67c5a935935629db3753b5bebea49319f3077

## Remove Harbinger usage

@4e599016d3a0fdeaf6b99ba65f78dfbffca3f1e5

## Adjusting host declaration for Airbrake

@51ce2089271feddb5503a3f587d81ad2581ac627

Instead of including the scheme/protocol, I needed it removed.

## Closing issue 204

@4920f7910982894ea78d6d850d9defc577a51337

Closes #204

$ ./script/close-issue 204

### CODE REVIEW

**Comment by jeremyf** [comment]
Tested locally.

File: config/initializers/airbrake.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+Airbrake.configure do |config|
+  config.api_key = ENV['AIRBRAKE_API_KEY']
```
Comment (danhorst) [inline config/initializers/airbrake.rb]: Should this be provided by [`Figero.env`](https://github.com/laserlemon/figaro#using-figaroenv)?
